### ISSUE TITLE
Cannot generate Bags

### ISSUE THREAD

**Issue by justrob1980** [LennardF1989/BG3-BagsOfSorting#3]
When I try to generate BagsOfSorting.pak it errors out. See below

PS C:\Users\rober\Downloads\New folder (2)> .\BG3.BagsofSorting.exe --generate-bags
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2023.6.14.1
Copyright (C) Microsoft Corp.

reading C:\Users\rober\Downloads\New folder (2)\Output\Bags\Public\GustavDev\Assets\Textures\Icons\BOS_b86dddf5b40144489745d47ffa9d8aab.png (64x64 B8G8R8A8_UNORM 2D) as (64x64,7 BC3_UNORM 2D a:NonPM)
writing C:\Users\rober\Downloads\New folder (2)\Output\Bags\Public\GustavDev\Assets\Textures\Icons\BOS_b86dddf5b40144489745d47ffa9d8aab.dds
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2023.6.14.1
Copyright (C) Microsoft Corp.

reading C:\Users\rober\Downloads\New folder (2)\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_b86dddf5b40144489745d47ffa9d8aab.png (380x380 B8G8R8A8_UNORM 2D) as (380x380,9 BC3_UNORM 2D a:NonPM)
writing C:\Users\rober\Downloads\New folder (2)\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_b86dddf5b40144489745d47ffa9d8aab.dds
Unhandled exception. System.IO.FileNotFoundException:
File name: 'C:\Users\rober\Downloads\New folder (2)\LSLibNative.dll'
   at LSLib.LS.BinUtils.CompressLZ4(Byte[] uncompressed, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.BinUtils.Compress(Byte[] uncompressed, CompressionMethod method, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.LSFWriter.Write(Resource resource)
   at BG3.BagsOfSorting.Program.ConvertLSXToLSF(String lsxPath, String lsfPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 624
   at BG3.BagsOfSorting.Program.GenerateRootTemplate(Bag bag, String outputPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 453
   at BG3.BagsOfSorting.Program.GenerateBag(BagConfiguration bagConfiguration, Bag bag) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 294
   at BG3.BagsOfSorting.Program.GenerateBags() in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 276
   at BG3.BagsOfSorting.Program.Main(String[] args) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 163

PS C:\Users\rober\Downloads\New folder (2)> dir
    Directory: C:\Users\rober\Downloads\New folder (2)
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/24/2023   9:26 AM                Content
d-----         8/25/2023  12:57 PM                Output
d-----         8/25/2023  12:56 PM                TXT files and Pouch of Wonders
-a----         8/24/2023   9:22 AM       22516807 BG3.BagsOfSorting.exe
-a----         8/24/2023   9:22 AM          15336 BG3.BagsOfSorting.pdb
-a----         8/24/2023   9:22 AM             31 Command - Add Bag.bat
-a----         8/24/2023   9:22 AM             42 Command - Export Atlas Icons.bat
-a----         8/24/2023   9:22 AM             37 Command - Generate Bags.bat
-a----         8/24/2023   9:22 AM         228352 LSLibNative.dll

PS C:\Users\rober\Downloads\New folder (2)> Get-ChildItem -Path "C:\Users\rober\Downloads\New folder (2)\Content\"
    Directory: C:\Users\rober\Downloads\New folder (2)\Content
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/24/2023   9:22 AM                Custom
d-----         8/24/2023   9:22 AM                Stock
-a----         8/24/2023   9:22 AM           3483 Bags.example.json
-a----         8/24/2023  10:08 AM           5730 Bags.json

PS C:\Users\rober\Downloads\New folder (2)> Get-ChildItem -Path "C:\Users\rober\Downloads\New folder (2)\Output\"
    Directory: C:\Users\rober\Downloads\New folder (2)\Output
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/25/2023  12:57 PM                Bags
d-----         8/24/2023   9:25 AM                Icons

PS C:\Users\rober\Downloads\New folder (2)> Get-ChildItem -Path "C:\Users\rober\Downloads\New folder (2)\Output\Bags\"
    Directory: C:\Users\rober\Downloads\New folder (2)\Output\Bags
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/25/2023  12:57 PM                Localization
d-----         8/25/2023  12:57 PM                Public
-a----         8/24/2023  10:08 AM           5730 Bags.json

PS C:\Users\rober\Downloads\New folder (2)>

**Comment by LennardF1989** [comment]
Are you using the latest version with a GUI?

**Comment by justrob1980** [comment]
No I was using the command line, I didn't realize their was a GUI version, lemme try that one.

**Comment by LennardF1989** [comment]
No problem, it got released I think around the same time you posted this :) Curious to hear if it fixes the problem for you!

**Comment by justrob1980** [comment]
OK so I now have a BagsOfSorting.pak file, what do I do with it? Putting it in C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\Data\ didn't put them in my inventory. I have the Pouch of Wonder, but when I instantiate it, it is empty, do I have to put the Bags of Sorting somehow in the Pouch of Wonder? If so, how?

**Comment by LennardF1989** [comment]
You put both the generated BagsOfSorting.pak and the PouchOfWonders.pak in your Data-folder, yes. If you used the manual TreasureTable.txt method before, remove that, it breaks the game.

Did your bag generation complete without any error? So the popup message in the end only said "Succesfully generated bags"? And no mention of errors and logs?

**Comment by justrob1980** [comment]
No when I use the GUI to generate, it does generate the PAK file, but I get [this error](https://imgur.com/a/OuekJui).

**Comment by LennardF1989** [comment]
Can you sent me your Bags.json?

**Comment by eladrin22** [comment]
I was encountering this issue. I think (based on the errors I see), you are not selecting generate/custom? I think the mod requires a specific image resolution for the icons.
When I clicked generate (Which I think generates the bag with a small version of the icon in the top right), I didn't get those errors.

Still not showing up in Bag of Wonders though. Json looks pretty standard Json file to me (though I am a courseware dev, not a game modder).
Can't upload Json, so just saved it as a text file.
[Bags.txt](https://github.com/LennardF1989/BG3-BagsOfSorting/files/12447803/Bags.txt)

**Comment by justrob1980** [comment]
> I was encountering this issue. I think (based on the errors I see), you are not selecting generate/custom? I think the mod requires a specific image resolution for the icons. When I clicked generate (Which I think generates the bag with a small version of the icon in the top right), I didn't get those errors.
> 
> Still not showing up in Bag of Wonders though. Json looks pretty standard Json file to me (though I am a courseware dev, not a game modder). Can't upload Json, so just saved it as a text file. [Bags.txt](https://github.com/LennardF1989/BG3-BagsOfSorting/files/12447803/Bags.

**Comment by justrob1980** [comment]
@eladrin22's suggestion turned out to be half of the problem. I did need to check the "Generate" boxes.
The other problem was that I had a special character, specifically an ampersand, in one of the Display Name.
Everytime I tried to generate bags even with the Generate boxes checked it would spit out an error about being unable to generate a box with a GUID that was not found in the JSON file. When I changed the ampersand to the word "and" it ran without error.

**Comment by LennardF1989** [comment]
v1.2.1 will have a fix for bad characters :)

**Comment by LennardF1989** [comment]
Could you give this version a spin? https://github.com/LennardF1989/BG3-BagsOfSorting/releases/tag/v1.2.1

Also be sure to update your Pouch of Wonders to v1.0.1 (if you use that)!

**Comment by justrob1980** [comment]
Can I copy my existing Bags.json to the new version of BagsOfSorting or do I need to build the bags brand new?

**Comment by Inmortuae** [comment]
> Can I copy my existing Bags.json to the new version of BagsOfSorting or do I need to build the bags brand new?

From my experience using it I have been able to keep my old bad by saving the Json and putting it back in to content after I reinstall the new version

**Comment by LennardF1989** [comment]
> Can I copy my existing Bags.json to the new version of BagsOfSorting or do I need to build the bags brand new?

You can move it over :)

**Comment by eladrin22** [comment]
for me, it appears to be working on the latest versions of both.
