### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by lofihigh** [LennardF1989/BG3-BagsOfSorting#6]
Hello, 

was trying out your mod, but I'm a little bit confused on the setup & usage.

![BG3 BagsOfSorting_zZWsQIsNNk](https://github.com/LennardF1989/BG3-BagsOfSorting/assets/142934809/ac0ebd5c-42e6-4dfc-946a-e20c8722057b)

I started with something simple, and I just want to create a bag to hold only torches, and have torches fill it automatically.

1. How do we constrain a bag to only allow certain items? is it based on the icon we set?

2. how does the auto pickup condition work? the description in readme seems to imply it can't work, but the field is there. 
what should a script to autofill torches look like?

**Comment by LennardF1989** [comment]
Both are technically supported by the game, but the game is not tagging all items with the appropriate metainfo to do it. Currently camping gear, keys, alchemy items and (most) scrolls are tagged by the game and can be auto-sorted/constrained.

So, to answer both questions: It does not, because we can't without additional mods that add tags to items.

**Comment by SM-26** [comment]
Just my 2 cents here, also had the same question in mine
so I did some digging inside the BagsBagsBags mod, and here are the tags I could find:

Scroll Case: "Tagged('SCROLL')"
Potion Pouch: "Tagged('POTION')"
Quiver: "Tagged('ARROW')"
Bag of Books: "Tagged('BOOK') and not Tagged('SCROLL')"
Grenade Satchel: "Tagged('GRENADE') or Tagged('ALCH_SOLUTION_GRENADE') or Tagged('EXPLOSIVES')"
Poisons Bag: "Tagged('ALCH_SOLUTION_COATING')"

**Comment by LennardF1989** [comment]
Maybe I can add these to a tooltip or something as a form of documentation.

**Comment by LennardF1989** [comment]
Added to v1.3.0 as a tooltip.
